### ISSUE TITLE
About renaming

### ISSUE THREAD

**Issue by LTJ233** [LinesGuy/lilToonToPoiyomiToon#1]
Can the converted poi material name be the same as the original material, while the original lil material is renamed? This saves the hassle of replacing materials.

**Comment by LinesGuy** [comment]
It wouldn't properly work to simply name the materials the same since the GUID's wouldn't be the same, thus the material wouldn't be replaced properly
However, I've modified the script so the lilToon material is now replaced by the Poiyomi material, instead of creating a new Poiyomi material from scratch.
A backup of the original lilToon material is created so the user still has access to it.
This has the same effect as the material automatically being applied, should save a lot of hassle for the user.
You can download the latest release [here](https://github.com/LinesGuy/lilToonToPoiyomiToon/releases)

**Comment by LTJ233** [comment]
Thanks so much!
